#include<iostream>
char a[20005],b[20005];
using namespace std;
int main()
{
int i,j,k,t,l,c[3],d[3],digits,sev,four;
scanf("%d",&t);
while(t--)
{
        scanf("%s%s",&a,&b);  
        //l=strlen(a);
        digits=sev=four=0;
        int x[10]={0},y[10]={0};
        i=0;
        while(a[i]!='\0')
        {
                  x[a[i]-48]++;
                  y[b[i]-48]++;
                  i++;
        }
        c[0]=x[0]+x[1]+x[2]+x[3];
        c[1]=x[5]+x[6];
        c[2]=x[8]+x[9];
        d[0]=y[0]+y[1]+y[2]+y[3];
        d[1]=y[5]+y[6];
        d[2]=y[8]+y[9];  
        if(x[7]>0)
        {
                  if(x[7]>d[1])
                  {
                               sev+=d[1];
                               x[7]-=d[1];
                               d[1]=0;
                  }
                  else
                  {
                      sev+=x[7];
                      d[1]-=x[7];
                      x[7]=0;
                  }
                  if(x[7]>d[0])
                  {
                            sev+=d[0];
                            x[7]-=d[0];
                            d[0]=0;
                  }
                  else
                  {
                      sev+=x[7];
                      d[0]-=x[7];
                      x[7]=0;
                  }
                  if(x[7]>y[4])
                  {
                               sev+=y[4];
                               x[7]-=y[4];
                               y[4]=0;
                  }
                  else
                  {
                      sev+=x[7];
                      y[4]-=x[7];
                      x[7]=0;
                  }
                  if(x[7]>y[7])
                  {
                               sev+=y[7];
                               x[7]-=y[7];
                               y[7]=0;
                  }
                  else
                  {
                      sev+=x[7];
                      y[7]-=x[7];
                      x[7]=0;
                  }
        }
        if(y[7]>0)
        {
                  if(y[7]>c[1])
                  {
                               sev+=c[1];
                               y[7]-=c[1];
                               c[1]=0;
                  }
                  else
                  {
                      sev+=y[7];
                      c[1]-=y[7];
                      y[7]=0;
                  }
                  if(y[7]>c[0])
                  {
                            sev+=c[0];
                            y[7]-=c[0];
                            c[0]=0;
                  }
                  else
                  {
                      sev+=y[7];
                      c[0]-=y[7];
                      y[7]=0;
                  }
                  if(y[7]>x[4])
                  {
                               sev+=x[4];
                               y[7]-=x[4];
                               x[4]=0;
                  }
                  else
                  {
                      sev+=y[7];
                      x[4]-=y[7];
                      y[7]=0;
                  }
                  if(y[7]>x[7])
                  {
                               sev+=x[7];
                               y[7]-=x[7];
                               x[7]=0;
                  }
                  else
                  {
                      sev+=y[7];
                      x[7]-=y[7];
                      y[7]=0;
                  }
        }
        if(x[4]>0)
        {
                  if(x[4]>d[0])
                  {
                               four+=d[0];
                               x[4]-=d[0];
                               d[0]=0;
                  }
                  else
                  {
                      four+=x[4];
                      d[0]-=x[4];
                      x[4]=0;
                  }
                  if(x[4]>y[4])
                  {
                               four+=y[4];
                               x[4]-=y[4];
                               y[4]=0;
                  }
                  else
                  {
                      four+=x[4];
                      y[4]-=x[4];
                      x[4]=0;
                  }
        }
        if(y[4]>0)
        {
                  if(y[4]>c[0])
                  {
                               four+=c[0];
                               y[4]-=c[0];
                               c[0]=0;
                  }
                  else
                  {
                      four+=y[4];
                      c[0]-=y[4];
                      y[4]=0;
                  }
                  if(y[4]>x[4])
                  {
                               four+=x[4];
                               y[4]-=x[4];
                               x[4]=0;
                  }
                  else
                  {
                      four+=y[4];
                      x[4]-=y[4];
                      y[4]=0;
                  }
        }
        for(i=0;i<sev;i++)
        cout<<"7";
        for(i=0;i<four;i++)
        cout<<"4";
        cout<<"\n";
}
}
                  
